import type { Metadata } from "next";
import {Capriola} from "next/font/google";
import "./globals.css";

import { ReactQueryProvider } from "./react-query-provider";
import {NuqsAdapter} from 'nuqs/adapters/next/app';
import { Toaster } from "@/components/ui/sonner";

const caPriola = Capriola({
  subsets: ["latin"],
  weight: ["400"], // o el peso que necesites
})

export const metadata: Metadata = {
  title: "Create Next App + DRF + Tanstack + ShadCn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${caPriola.className} antialiased`}
      >
        <NuqsAdapter>
          <ReactQueryProvider>
            {children}
            <Toaster />
          </ReactQueryProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
