# Generated by Django 5.1.5 on 2025-11-26 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_alter_subcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio en EUR', max_digits=12)),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='products')),
                ('refundpolicy', models.CharField(choices=[('30-días', '30-días'), ('14-días', '14-días'), ('7-días', '7-días'), ('1-días', '1-días'), ('no-reembolso', 'no-reembolso')], default='30-días', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='shop.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='shop.subcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
