# Generated by Django 5.1.5 on 2025-11-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_tag_alter_product_subcategory_product_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
