# Generated by Django 5.1.5 on 2025-12-03 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_tag_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='products/'),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre Tienda, Este es el nombre de la tienda (e.g Tienda Antonio)', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Este es el subdominio de la tienda (e.g [slug].funroad.com)', unique=True)),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='tenants/')),
                ('stripeAccountId', models.CharField(max_length=255)),
                ('stripeDetailsSubmitted', models.BooleanField(default=False, help_text='Tu no puedes crear products has que valides, los detalles de Stripe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arrendatario',
                'verbose_name_plural': 'Arrendatarios',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tenant', to='shop.tenant'),
        ),
    ]
