# Generated by Django 5.1.5 on 2025-12-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_imagen_tenant_product_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
    ]
