import type { Metadata } from "next";
import { Birthstone, Capriola} from "next/font/google";
import "./globals.css";

const caPriola = Capriola({
  subsets: ["latin"],
  weight: ["400"], // o el peso que necesites
})

export const metadata: Metadata = {
  title: "Create Next App + DRF + Tanstack + ShadCn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${caPriola.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
